---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: stage
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: samuervin/nginx:v0.1.4
          ports:
            - containerPort: 80